# Generated by Django 4.2.4 on 2023-08-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goglocalAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPI',
        ),
    ]
